### ISSUE TITLE
Not Found in Hunter

### ISSUE THREAD

**Issue by jakesylvestre** [daminetreg/lib-cpp-pre#7]
As per the [documentation](http://daminetreg.github.io/lib-cpp-pre/html/index.html) this should be available in Hunter by doing:

```
hunter_add_package(lib-cpp-pre)
find_package(lib-cpp-pre 1.3.7 REQUIRED)
```

I'm getting:

```
-- [hunter *** DEBUG *** 2020-01-24T04:09:03] File not found (injected package): /home/debugger/.hunter/_Base/Download/Hunter/0.23.214/e14bc15/Unpacked/cmake/projects/lib-cpp-pre/hunter.cmake
-- [hunter *** DEBUG *** 2020-01-24T04:09:03] Injected package 'lib-cpp-pre'
-- [hunter *** DEBUG *** 2020-01-24T04:09:03] lib-cpp-pre versions available: []
```

Hunter Version:
```
-- [hunter *** DEBUG *** 2020-01-24T04:09:00] Variables from HunterGate:
-- [hunter *** DEBUG *** 2020-01-24T04:09:00]   HUNTER_GATE_ROOT: /home/debugger/.hunter
-- [hunter *** DEBUG *** 2020-01-24T04:09:00]   HUNTER_GATE_VERSION: 0.23.214
-- [hunter *** DEBUG *** 2020-01-24T04:09:00]   HUNTER_GATE_SHA1: e14bc153a7f16d6a5eeec845fb0283c8fad8c358
```

**Comment by jakesylvestre** [comment]
Alright, so I'm not sure where this got removed or why (I couldn't find any reference in either hunter repo), but I found an old project by @daminetreg 
/
 using `hunter_add_package(lib-cpp-pre)` [here](https://github.com/daminetreg/1h00-distributedjson/blob/b7fcdd4f301ad9636e03b34f8224b34fd93ec34a/CMakeLists.txt#L23)

which appears to link to [this](https://github.com/daminetreg/hunter/blob/releases/sam3-support-clang/cmake/projects/lib-cpp-pre/hunter.cmake) cmake with these versions:

```

hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.2.2"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/v1.2.2.tar.gz" 
    SHA1 6733a0abd9f74bd67e4ef521e7677ad9437cdba1 
)

hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.3.2"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/v1.3.2.tar.gz" 
    SHA1 fef5d597594a62f25bc4ae71608d1f0d70f24a56 
)

hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.3.3"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/v1.3.3.tar.gz" 
    SHA1 28e5f813b255d6a2e5592d0cf80225ffaeef3f8e 
)

hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.3.5"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/v1.3.5.tar.gz" 
    SHA1 3b32577823fd7fdbe448d13e6011672e7a8ef143 
)


hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.3.6"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/v1.3.6.tar.gz" 
    SHA1 044fb7ef957d09ca3abca22597efef9ab61f5693
)

hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.3.7"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/v1.3.7.tar.gz" 
    SHA1 ad0e7ee9332d11452412a06d425a1df27ee3e79e
)

hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.3.8"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/v1.3.8.tar.gz" 
    SHA1 ef82e6c456ca903c11f1dca0f9f33cdb70efe61e 
)

hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.4.0"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/v1.4.0.tar.gz" 
    SHA1 fac0e14d6111118f230cff85e23c72fccb3b07cd 
)

hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.4.1"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/v1.4.1.tar.gz" 
    SHA1 d7dd80f6c9b939b39914194a0d6682399a793950 
)

hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.4.2"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/v1.4.2.tar.gz" 
    SHA1 68ab8f6f58fd01680e981dc855ea83778a748872 
)

hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.4.3"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/v1.4.3.tar.gz" 
    SHA1 b4494c774b314d8c18759f53933f6d59352dc947 
)

hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.4.4"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/feature/updating-deps.tar.gz" 
    SHA1 6e87e7b8eaecb5e48509c84e1782e0377b4eb87c 
)
``` 

Anyone that adds this to their project

```
hunter_add_version(
    PACKAGE_NAME lib-cpp-pre
    VERSION "1.4.4"
    URL "https://github.com/daminetreg/lib-cpp-pre/archive/feature/updating-deps.tar.gz" 
    SHA1 6e87e7b8eaecb5e48509c84e1782e0377b4eb87c 
)
``` 

should be good to go

**Comment by daminetreg** [comment]
Dear @jakesyl,

Thank you very much. Actually it never went into the official hunter, or at least I think I never pushed it to the official hunter.

I went to revamp the whole lib-cpp-pre into smaller libs that can be consumed independently, and don't plan on upgrading this flavour of lib-cpp-pre in the future.

The new development which is C++17 (which contains already fixes) are here : https://github.com/cpp-pre

What is you usage of lib-cpp-pre ? May I help you transition

**Comment by jakesylvestre** [comment]
Thanks for the quick reply! I'm using it to statically iterate through elements in a struct based on [this](https://stackoverflow.com/a/34687781/1011803)

@daminetreg I hope you don't mind, I submitted it to hunter here cpp-pm/hunter#146 / cpp-pm/hunter-testing#44

**Comment by daminetreg** [comment]
That's really kind from you ^^, I saw it at hunter, as I'm contributing to hunter too. 

However I think you would benefit from migrating on this one : https://github.com/cpp-pre/json/tree/master/pre/fusion

At first this lib was my personal toolkit, it was named swak (swiss army knife) but then with 2 other colleagues we brought to it more functionality and went to `pre::`

Now I migrated the part that you use in smaller chunks. For example pre::fusion::for_each_member is in https://github.com/cpp-pre/json/tree/master/pre/fusion.

The issue with the current offering of pre that you provided to hunter, is that there is too much unrelated things in it. And I'm not convinced it makes sense to support stuffs like the smart enums anymore.

I should have warned on the readme, but I was a bit in miss of time these 2 last years.

**Comment by jakesylvestre** [comment]
Got it! I'll close them. Thanks!

**Comment by daminetreg** [comment]
If you need any assistance in bringing the others in hunter, I'm your guy, because currently it builds and can be packaged with nxxm, but there is no direct CMakeLists.txt in the repo, I don't mind adding some if needed.

**Comment by jakesylvestre** [comment]
@daminetreg if it wouldn't be too much trouble that'd be awesome and I can add back to hunter (looks like you recently had one in there)

**Comment by jakesylvestre** [comment]
Also just checked out nxxm, this is awesome! Hadn't heard of it

**Comment by daminetreg** [comment]
Cool that you like it. ^^ I plan to opensource it soon, I'm currently building a new version as the wasm support is no more working due to emscripten changes (I have one on my dev machine that works, will be published next week).

nxxm autogenerate cmakelistst in `build/recipe`, but don't care if there is one (unless specified to care), so for your use I could pull the generated cmake in the main repo, this shouldn't block you from using it with hunter.

But a good decision, would be even to extract pre::fusion::for_each_member to it's own lib that only depends on boost headers.

**Comment by daminetreg** [comment]
Ultimately nxxm should be able to generate hunter package from anything that looks like C++, but I'm currently trying to build a team to go in this direction.

**Comment by jakesylvestre** [comment]
Cool! Yeah - if you've got an org would love to help out, just tag me on the issue. Obviously some stuff to figure out implementation wise, but sounds interesting

**Comment by daminetreg** [comment]
Thank you ! The org is here : https://github.com/nxxm, as soon as I released the next version I'll ping you.

In the meantime I will put a cmakelists and pre::fusion::for_each_member in a separate repo.
